import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  // next-env.d.ts is regenerated by Next.js on every build; linting a generated
  // file produces an error nobody can fix without it coming straight back.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
];

export default config;
